[package]
name = "peperspray"
version = "0.1.2"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
toml = "1.1.2"
log = "0.4.29"
serde_json = "1.0.150"
chrono = { version = "0.4.44", features = ["serde"] }
uuid = { version = "1.23.1", features = ["v4", "serde"] }
nix = { version = "0.31.3", features = ["user"] }
which = "8.0.2"
sha2 = "0.10.9"
reqwest = { version = "0.12.24", features = ["blocking", "json"], default-features = false }
regex = "1.12.2"

[dev-dependencies]
tempfile = "3.27.0"
