mode = "learn"

[[users]]
uid = 1000
groups = ["aws", "ssh"]

[[protected_groups]]
name = "aws"
paths = [
    "~/.aws"
]

[[protected_groups]]
name = "ssh"
paths = [
    "~/.ssh"
]

[[allow_rules]]
name = "Allow AWS CLI"
uid = 1000
exe = "/usr/bin/aws"
path_group = "aws"

[[allow_rules]]
name = "Allow SSH client"
uid = 1000
exe = "/usr/bin/ssh"
path_group = "ssh"
